# Generated by Django 5.1.4 on 2026-03-20 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BNSSSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act', models.CharField(choices=[('BNS', 'Bharatiya Nyaya Sanhita'), ('BNSS', 'Bharatiya Nagarik Suraksha Sanhita'), ('BSA', 'Bharatiya Sakshya Adhiniyam'), ('IPC', 'Indian Penal Code (Legacy)'), ('CrPC', 'Code of Criminal Procedure (Legacy)')], max_length=10)),
                ('section_number', models.CharField(max_length=20)),
                ('section_title', models.CharField(max_length=500)),
                ('section_text', models.TextField()),
                ('simplified_text', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('related_sections', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BNSS Section',
                'db_table': 'bnss_sections',
                'ordering': ['act', 'section_number'],
                'unique_together': {('act', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='LegalQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_query', models.TextField()),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('translated_query', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_entities', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Query',
                'verbose_name_plural': 'Legal Queries',
                'db_table': 'legal_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_response', models.TextField()),
                ('filtered_response', models.TextField()),
                ('disclaimer_added', models.BooleanField(default=True)),
                ('sections_mapped', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_ethical', models.BooleanField(default=True)),
                ('ethics_flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='legal_query.legalquery')),
            ],
            options={
                'verbose_name': 'Query Response',
                'db_table': 'query_responses',
            },
        ),
        migrations.CreateModel(
            name='QuerySectionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField()),
                ('mapping_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_mappings', to='legal_query.legalquery')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_mappings', to='legal_query.bnsssection')),
            ],
            options={
                'db_table': 'query_section_mappings',
                'ordering': ['-relevance_score'],
            },
        ),
    ]
