# Generated by Django 5.1.4 on 2026-04-22 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_query', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bnsssection',
            options={'ordering': ['act', 'section_number']},
        ),
        migrations.AlterModelOptions(
            name='legalquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='queryresponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='querysectionmapping',
            options={},
        ),
        migrations.RenameField(
            model_name='queryresponse',
            old_name='filtered_response',
            new_name='disclaimer',
        ),
        migrations.RenameField(
            model_name='queryresponse',
            old_name='raw_response',
            new_name='factual_summary',
        ),
        migrations.RenameField(
            model_name='queryresponse',
            old_name='ethics_flags',
            new_name='related_sections',
        ),
        migrations.RemoveField(
            model_name='legalquery',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='legalquery',
            name='extracted_entities',
        ),
        migrations.RemoveField(
            model_name='legalquery',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='legalquery',
            name='processing_time_ms',
        ),
        migrations.RemoveField(
            model_name='legalquery',
            name='translated_query',
        ),
        migrations.RemoveField(
            model_name='queryresponse',
            name='disclaimer_added',
        ),
        migrations.RemoveField(
            model_name='queryresponse',
            name='is_ethical',
        ),
        migrations.RemoveField(
            model_name='queryresponse',
            name='sections_mapped',
        ),
        migrations.RemoveField(
            model_name='querysectionmapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='querysectionmapping',
            name='mapping_reason',
        ),
        migrations.AddField(
            model_name='legalquery',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='legalquery',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalquery',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queryresponse',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queryresponse',
            name='processing_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queryresponse',
            name='response_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='querysectionmapping',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bnsssection',
            name='act',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bnsssection',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bnsssection',
            name='simplified_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalquery',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='legalquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queryresponse',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='querysectionmapping',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='querysectionmapping',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_query.bnsssection'),
        ),
    ]
