import os
import logging
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    HRFlowable, Table, TableStyle
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.graphics.shapes import Drawing, Rect, String, Circle
from reportlab.graphics import renderPDF
from django.conf import settings

logger = logging.getLogger(__name__)

LANGUAGE_STRINGS = {
    'en': {
        'draft_notice': '⚠ DRAFT — FOR REFERENCE ONLY — NOT A LEGAL DOCUMENT ⚠',
        'generated_by': 'Generated by CaseIQ Legal Awareness Platform',
        'to': 'TO,',
        'subject': 'SUBJECT',
        'complainant_details': 'COMPLAINANT DETAILS',
        'incident_details': 'INCIDENT DETAILS',
        'name': 'Name',
        'address': 'Address',
        'phone': 'Phone',
        'date': 'Date',
        'location': 'Location',
        'description': 'Description of Incident',
        'accused': 'Details of Accused (if known)',
        'witnesses': 'Witnesses',
        'evidence': 'Evidence',
        'sections': 'Applicable Legal Sections',
        'draft_text': 'AI-GENERATED DRAFT TEXT',
        'relief': 'Relief Sought',
        'declaration_title': 'DECLARATION',
        'declaration_text': 'I, the undersigned, do hereby solemnly declare that the information provided above is true and correct to the best of my knowledge and belief. I understand that providing false information is punishable under law.',
        'place': 'Place',
        'signature': 'Signature',
        'not_provided': 'Not provided',
        'disclaimer': 'DISCLAIMER: This document is generated by CaseIQ for legal awareness purposes only. CaseIQ does not provide legal advice. This draft should be reviewed by a qualified advocate before submission.',
        'regarding': 'regarding incident at',
        'on': 'on',
        'police_station': 'Police Station',
    },
    'hi': {
        'draft_notice': '⚠ मसौदा — केवल संदर्भ के लिए — यह कानूनी दस्तावेज़ नहीं है ⚠',
        'generated_by': 'CaseIQ कानूनी जागरूकता प्लेटफ़ॉर्म द्वारा तैयार',
        'to': 'सेवा में,',
        'subject': 'विषय',
        'complainant_details': 'शिकायतकर्ता का विवरण',
        'incident_details': 'घटना का विवरण',
        'name': 'नाम',
        'address': 'पता',
        'phone': 'फ़ोन',
        'date': 'तारीख',
        'location': 'स्थान',
        'description': 'घटना का विवरण',
        'accused': 'आरोपी का विवरण (यदि ज्ञात हो)',
        'witnesses': 'गवाह',
        'evidence': 'साक्ष्य',
        'sections': 'लागू कानूनी धाराएं',
        'draft_text': 'AI-जनित मसौदा पाठ',
        'relief': 'मांगी गई राहत',
        'declaration_title': 'घोषणा',
        'declaration_text': 'मैं, नीचे हस्ताक्षरकर्ता, एतद्द्वारा सत्यनिष्ठा से घोषणा करता/करती हूं कि ऊपर दी गई जानकारी मेरी जानकारी और विश्वास के अनुसार सत्य और सही है।',
        'place': 'स्थान',
        'signature': 'हस्ताक्षर',
        'not_provided': 'उपलब्ध नहीं',
        'disclaimer': 'अस्वीकरण: यह दस्तावेज़ CaseIQ द्वारा केवल कानूनी जागरूकता के उद्देश्य से तैयार किया गया है। CaseIQ कानूनी सलाह नहीं देता।',
        'regarding': 'घटना के संबंध में',
        'on': 'को',
        'police_station': 'थाना',
    },
    'mr': {
        'draft_notice': '⚠ मसुदा — केवल संदर्भासाठी — हे कायदेशीर दस्तऐवज नाही ⚠',
        'generated_by': 'CaseIQ कायदेशीर जागरूकता प्लॅटफॉर्मद्वारे तयार केले',
        'to': 'सेवेत,',
        'subject': 'विषय',
        'complainant_details': 'तक्रारदाराचा तपशील',
        'incident_details': 'घटनेचा तपशील',
        'name': 'नाव',
        'address': 'पत्ता',
        'phone': 'फोन',
        'date': 'तारीख',
        'location': 'ठिकाण',
        'description': 'घटनेचे वर्णन',
        'accused': 'आरोपीचा तपशील (माहीत असल्यास)',
        'witnesses': 'साक्षीदार',
        'evidence': 'पुरावे',
        'sections': 'लागू कायदेशीर कलमे',
        'draft_text': 'AI-निर्मित मसुदा मजकूर',
        'relief': 'मागितलेली दाद',
        'declaration_title': 'घोषणा',
        'declaration_text': 'मी, खालील स्वाक्षरीकर्ता, येथे प्रामाणिकपणे घोषित करतो/करते की वरील माहिती माझ्या माहिती आणि विश्वासानुसार सत्य आणि बरोबर आहे.',
        'place': 'ठिकाण',
        'signature': 'स्वाक्षरी',
        'not_provided': 'उपलब्ध नाही',
        'disclaimer': 'अस्वीकरण: हे दस्तऐवज CaseIQ द्वारे केवळ कायदेशीर जागरूकतेसाठी तयार केले आहे. CaseIQ कायदेशीर सल्ला देत नाही.',
        'regarding': 'घटनेबद्दल',
        'on': 'रोजी',
        'police_station': 'पोलीस ठाणे',
    }
}


class PDFService:

    def _get_strings(self, language):
        return LANGUAGE_STRINGS.get(language, LANGUAGE_STRINGS['en'])

    def _create_logo_header(self, strings):
        """Create CaseIQ letterhead as a table"""
        logo_style = ParagraphStyle(
            'Logo',
            fontSize=22,
            fontName='Helvetica-Bold',
            textColor=colors.HexColor('#1a1a2e'),
            alignment=TA_LEFT,
        )
        tagline_style = ParagraphStyle(
            'Tagline',
            fontSize=8,
            fontName='Helvetica',
            textColor=colors.HexColor('#666666'),
            alignment=TA_LEFT,
        )
        date_style = ParagraphStyle(
            'Date',
            fontSize=9,
            fontName='Helvetica',
            textColor=colors.HexColor('#333333'),
            alignment=TA_RIGHT,
        )

        logo_cell = [
            Paragraph('<font color="#e94560">Case</font><font color="#1a1a2e">IQ</font>', logo_style),
            Paragraph('AI-Powered Legal Awareness Platform', tagline_style),
        ]
        date_cell = [
            Paragraph(f'{strings["generated_by"]}', date_style),
            Paragraph(f'{strings["date"]}: {datetime.now().strftime("%d %B %Y")}', date_style),
        ]

        header_table = Table(
            [[logo_cell, date_cell]],
            colWidths=[9*cm, 9*cm]
        )
        header_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8f9fa')),
            ('ROUNDEDCORNERS', [5, 5, 5, 5]),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (0, -1), 10),
            ('RIGHTPADDING', (-1, 0), (-1, -1), 10),
        ]))
        return header_table

    def generate_complaint_pdf(self, complaint, output_path, language=None):
        try:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            lang = language or complaint.language or 'en'
            # Use english for non-supported languages
            if lang not in ('en', 'hi', 'mr'):
                lang = 'en'
            strings = self._get_strings(lang)

            doc = SimpleDocTemplate(
                output_path,
                pagesize=A4,
                rightMargin=2*cm,
                leftMargin=2*cm,
                topMargin=1.5*cm,
                bottomMargin=2*cm,
            )

            styles = getSampleStyleSheet()

            title_style = ParagraphStyle(
                'Title', parent=styles['Normal'],
                fontSize=14, spaceAfter=4,
                alignment=TA_CENTER,
                textColor=colors.HexColor('#1a1a2e'),
                fontName='Helvetica-Bold',
            )
            body_style = ParagraphStyle(
                'Body', parent=styles['Normal'],
                fontSize=10, spaceAfter=6,
                alignment=TA_JUSTIFY,
                fontName='Helvetica', leading=14,
            )
            label_style = ParagraphStyle(
                'Label', parent=styles['Normal'],
                fontSize=10, fontName='Helvetica-Bold',
                textColor=colors.HexColor('#1a1a2e'),
                spaceAfter=4,
            )
            disclaimer_style = ParagraphStyle(
                'Disclaimer', parent=styles['Normal'],
                fontSize=8, alignment=TA_CENTER,
                textColor=colors.HexColor('#cc0000'),
                fontName='Helvetica-Bold',
            )
            section_header_style = ParagraphStyle(
                'SectionHeader', parent=styles['Normal'],
                fontSize=10, fontName='Helvetica-Bold',
                textColor=colors.white,
                alignment=TA_LEFT,
                spaceAfter=0,
            )

            story = []

            # CaseIQ Letterhead
            story.append(self._create_logo_header(strings))
            story.append(Spacer(1, 0.15*inch))

            # Colored banner for document type
            complaint_type_display = dict(complaint.COMPLAINT_TYPE_CHOICES).get(
                complaint.complaint_type, complaint.complaint_type.upper()
            )
            banner_data = [[Paragraph(complaint_type_display.upper(), section_header_style)]]
            banner = Table(banner_data, colWidths=[17*cm])
            banner.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1a1a2e')),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ]))
            story.append(banner)
            story.append(Spacer(1, 0.05*inch))

            # Draft warning
            story.append(Paragraph(strings['draft_notice'], disclaimer_style))
            story.append(Spacer(1, 0.1*inch))

            # TO section
            police_station = getattr(complaint, 'police_station_name', '') or '[Police Station Name]'
            police_address = getattr(complaint, 'police_station_address', '') or '[District], [State]'
            authority = self._get_authority(complaint.complaint_type, police_station, police_address)

            story.append(Paragraph(strings['to'], label_style))
            story.append(Paragraph(authority, body_style))
            story.append(Spacer(1, 0.1*inch))

            # Subject
            story.append(Paragraph(
                f'<b>{strings["subject"]}:</b> {complaint_type_display} '
                f'{strings["regarding"]} {complaint.incident_location} '
                f'{strings["on"]} {complaint.incident_date}',
                body_style
            ))
            story.append(Spacer(1, 0.1*inch))

            # Complainant details — colored header
            self._add_section_header(story, strings['complainant_details'])
            complainant_data = [
                [f'{strings["name"]}:', complaint.complainant_name],
                [f'{strings["address"]}:', complaint.complainant_address],
                [f'{strings["phone"]}:', complaint.complainant_phone or strings['not_provided']],
            ]
            story.append(self._make_table(complainant_data))
            story.append(Spacer(1, 0.1*inch))

            # Incident details
            self._add_section_header(story, strings['incident_details'])
            incident_data = [
                [f'{strings["date"]}:', str(complaint.incident_date)],
                [f'{strings["location"]}:', complaint.incident_location],
            ]
            story.append(self._make_table(incident_data))
            story.append(Spacer(1, 0.05*inch))
            story.append(Paragraph(f'<b>{strings["description"]}:</b>', label_style))
            story.append(Paragraph(complaint.incident_description, body_style))

            if complaint.accused_details:
                story.append(Paragraph(f'<b>{strings["accused"]}:</b>', label_style))
                story.append(Paragraph(complaint.accused_details, body_style))

            if complaint.witnesses:
                story.append(Paragraph(f'<b>{strings["witnesses"]}:</b>', label_style))
                story.append(Paragraph(complaint.witnesses, body_style))

            if complaint.evidence_description:
                story.append(Paragraph(f'<b>{strings["evidence"]}:</b>', label_style))
                story.append(Paragraph(complaint.evidence_description, body_style))

            if complaint.applicable_sections:
                story.append(Paragraph(
                    f'<b>{strings["sections"]}:</b> {", ".join(complaint.applicable_sections)}',
                    body_style
                ))

            story.append(Spacer(1, 0.1*inch))

            # AI Draft
            if complaint.generated_draft:
                self._add_section_header(story, strings['draft_text'])
                story.append(Spacer(1, 0.05*inch))
                draft_text = complaint.generated_draft.replace('\n', '<br/>')
                story.append(Paragraph(draft_text, body_style))
                story.append(Spacer(1, 0.1*inch))

            # Relief
            if complaint.relief_sought:
                story.append(Paragraph(f'<b>{strings["relief"]}:</b>', label_style))
                story.append(Paragraph(complaint.relief_sought, body_style))
                story.append(Spacer(1, 0.1*inch))

            # Declaration
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1a1a2e')))
            story.append(Spacer(1, 0.1*inch))
            story.append(Paragraph(strings['declaration_title'], label_style))
            story.append(Paragraph(strings['declaration_text'], body_style))
            story.append(Spacer(1, 0.25*inch))

            # Signature block
            sig_data = [
                [f'{strings["place"]}: _______________', f'{strings["signature"]}: _______________'],
                [f'{strings["date"]}: _______________', f'{strings["name"]}: {complaint.complainant_name}'],
            ]
            sig_table = Table(sig_data, colWidths=[8*cm, 8*cm])
            sig_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(sig_table)
            story.append(Spacer(1, 0.15*inch))

            # Footer
            story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#e94560')))
            story.append(Spacer(1, 0.05*inch))
            story.append(Paragraph(strings['disclaimer'], disclaimer_style))

            doc.build(story)
            logger.info(f"PDF generated: {output_path}")
            return True

        except Exception as e:
            logger.error(f"PDF generation error: {e}", exc_info=True)
            return False

    def _add_section_header(self, story, title):
        style = ParagraphStyle(
            'SH', fontSize=10, fontName='Helvetica-Bold',
            textColor=colors.white, spaceAfter=0,
        )
        data = [[Paragraph(title, style)]]
        table = Table(data, colWidths=[17*cm])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#e94560')),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.05*inch))

    def _make_table(self, data):
        table = Table(data, colWidths=[4*cm, 13*cm])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('LEFTPADDING', (0, 0), (0, -1), 6),
        ]))
        return table

    def _get_authority(self, complaint_type, police_station, police_address):
        base = {
            'fir': f'The Station House Officer,\n{police_station},\n{police_address}',
            'written_complaint': f'The Superintendent of Police,\n{police_station},\n{police_address}',
            'magistrate_complaint': f'The Judicial Magistrate First Class,\n[Court Name],\n{police_address}',
            'consumer_complaint': f'The Consumer Disputes Redressal Commission,\n{police_address}',
            'cyber_complaint': f'The Cyber Crime Cell,\n{police_station},\n{police_address}',
        }
        return base.get(complaint_type, f'The Concerned Authority,\n{police_station},\n{police_address}')


pdf_service = PDFService()