# Generated by Django 6.0.2 on 2026-02-19 06:26

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=50, unique=True)),
                ("year", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g., IPC replaced by BNS",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="laws.act",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Acts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LawPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="law_pdfs/%Y/%m/")),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="India Code or official government source URL",
                        null=True,
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("sections_extracted", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdfs",
                        to="laws.act",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LawSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("punishment", models.TextField(blank=True, null=True)),
                ("cognizable", models.BooleanField(default=False)),
                ("bailable", models.BooleanField(default=False)),
                ("compoundable", models.BooleanField(default=False)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                (
                    "replaces_section",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'IPC 302' if this is BNS 103",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="laws.act",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cognizable"], name="laws_lawsec_cogniza_3a3e0c_idx"
                    ),
                    models.Index(
                        fields=["bailable"], name="laws_lawsec_bailabl_10e564_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="laws_lawsec_is_acti_f51533_idx"
                    ),
                ],
                "unique_together": {("act", "section_number")},
            },
        ),
    ]
