# Generated by Django 5.1.4 on 2026-03-20 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='knowledge_base.legalcategory')),
            ],
            options={
                'verbose_name_plural': 'Legal Categories',
                'db_table': 'legal_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CitizenRight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('constitutional_reference', models.CharField(blank=True, max_length=255)),
                ('practical_steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights', to='knowledge_base.legalcategory')),
            ],
            options={
                'verbose_name': "Citizen's Right",
                'db_table': 'citizen_rights',
            },
        ),
        migrations.CreateModel(
            name='LegalProvision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('act_name', models.CharField(max_length=255)),
                ('section_reference', models.CharField(max_length=100)),
                ('full_text', models.TextField()),
                ('simplified_text', models.TextField()),
                ('plain_language_summary', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('applicable_to', models.JSONField(default=list)),
                ('embedding_text', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisions', to='knowledge_base.legalcategory')),
            ],
            options={
                'verbose_name': 'Legal Provision',
                'db_table': 'legal_provisions',
                'ordering': ['act_name', 'section_reference'],
            },
        ),
    ]
