# Generated by Django 5.1.4 on 2026-03-20 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Step-by-step Guide'), ('faq', 'FAQ'), ('infographic', 'Infographic'), ('video_script', 'Video Script')], max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('target_audience', models.CharField(default='citizen', max_length=255)),
                ('language', models.CharField(default='en', max_length=5)),
                ('tags', models.JSONField(default=list)),
                ('related_laws', models.JSONField(default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Educational Content',
                'db_table': 'educational_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalNewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('related_sections', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Legal News Article',
                'db_table': 'legal_news',
                'ordering': ['-published_at'],
            },
        ),
    ]
