"""Complaint PDF rendering (reportlab). Faithful port of the original letterhead
layout; trimmed language strings to en/hi/mr for brevity. Runs in a worker thread
because reportlab is synchronous.
"""
from __future__ import annotations

import os
from datetime import datetime

import anyio
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.models.complaint import Complaint, ComplaintType

_AUTHORITY = {
    ComplaintType.FIR: "The Station House Officer",
    ComplaintType.WRITTEN: "The Superintendent of Police",
    ComplaintType.MAGISTRATE: "The Judicial Magistrate First Class",
    ComplaintType.CONSUMER: "The Consumer Disputes Redressal Commission",
    ComplaintType.CYBER: "The Cyber Crime Cell",
}
_DISCLAIMER = (
    "DISCLAIMER: Generated by CaseIQ for legal-awareness purposes only. This is a DRAFT, "
    "not legal advice, and should be reviewed by a qualified advocate before submission."
)


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "body": ParagraphStyle("Body", parent=base["Normal"], fontSize=10, leading=14, alignment=TA_JUSTIFY),
        "label": ParagraphStyle("Label", parent=base["Normal"], fontSize=10, fontName="Helvetica-Bold",
                                 textColor=colors.HexColor("#1a1a2e")),
        "disclaimer": ParagraphStyle("Disc", parent=base["Normal"], fontSize=8, alignment=TA_CENTER,
                                     textColor=colors.HexColor("#cc0000"), fontName="Helvetica-Bold"),
        "sec": ParagraphStyle("Sec", fontSize=10, fontName="Helvetica-Bold", textColor=colors.white),
    }


def _section_header(title: str, st: dict) -> Table:
    t = Table([[Paragraph(title, st["sec"])]], colWidths=[17 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#e94560")),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def _render(complaint: Complaint, path: str) -> bool:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    st = _styles()
    doc = SimpleDocTemplate(path, pagesize=A4, rightMargin=2 * cm, leftMargin=2 * cm,
                            topMargin=1.5 * cm, bottomMargin=2 * cm)
    story: list = []
    logo = ParagraphStyle("Logo", fontSize=20, fontName="Helvetica-Bold", alignment=TA_LEFT)
    story.append(Paragraph('<font color="#e94560">Case</font><font color="#1a1a2e">IQ</font>', logo))
    story.append(Paragraph("AI-Powered Legal Awareness Platform", st["body"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now():%d %B %Y}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    authority = _AUTHORITY.get(complaint.complaint_type, "The Concerned Authority")
    story.append(Paragraph("TO,", st["label"]))
    story.append(Paragraph(f"{authority},<br/>{complaint.police_station_name or '[Police Station]'}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        f"<b>SUBJECT:</b> {complaint.complaint_type.value.replace('_', ' ').title()} "
        f"regarding incident at {complaint.incident_location} on {complaint.incident_date}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    story.append(_section_header("COMPLAINANT DETAILS", st))
    story.append(Spacer(1, 0.05 * inch))
    for lbl, val in [("Name", complaint.complainant_name), ("Address", complaint.complainant_address),
                     ("Phone", complaint.complainant_phone or "Not provided")]:
        story.append(Paragraph(f"<b>{lbl}:</b> {val}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    story.append(_section_header("INCIDENT DETAILS", st))
    story.append(Spacer(1, 0.05 * inch))
    story.append(Paragraph(f"<b>Description:</b> {complaint.incident_description}", st["body"]))
    if complaint.accused_details:
        story.append(Paragraph(f"<b>Accused:</b> {complaint.accused_details}", st["body"]))
    if complaint.applicable_sections:
        story.append(Paragraph(f"<b>Sections:</b> {', '.join(complaint.applicable_sections)}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    if complaint.generated_draft:
        story.append(_section_header("AI-GENERATED DRAFT TEXT", st))
        story.append(Spacer(1, 0.05 * inch))
        story.append(Paragraph(complaint.generated_draft.replace("\n", "<br/>"), st["body"]))
        story.append(Spacer(1, 0.1 * inch))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph("DECLARATION", st["label"]))
    story.append(Paragraph(
        "I solemnly declare that the information provided above is true and correct to the best of "
        "my knowledge. I understand that providing false information is punishable under law.", st["body"]))
    story.append(Spacer(1, 0.25 * inch))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#e94560")))
    story.append(Paragraph(_DISCLAIMER, st["disclaimer"]))
    doc.build(story)
    return True


async def generate_complaint_pdf(complaint: Complaint, path: str) -> bool:
    return await anyio.to_thread.run_sync(_render, complaint, path)
