"""Complaint PDF rendering (reportlab). Faithful port of the original letterhead
layout; trimmed language strings to en/hi/mr for brevity. Runs in a worker thread
because reportlab is synchronous.
"""
from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path
from xml.sax.saxutils import escape

import anyio
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.models.complaint import Complaint, ComplaintType

_AUTHORITY = {
    ComplaintType.FIR: "The Station House Officer",
    ComplaintType.WRITTEN: "The Superintendent of Police",
    ComplaintType.MAGISTRATE: "The Judicial Magistrate First Class",
    ComplaintType.CONSUMER: "The Consumer Disputes Redressal Commission",
    ComplaintType.CYBER: "The Cyber Crime Cell",
}
# FIXED 2026-09-01: complaint_type.value.replace('_', ' ').title() turned
# "fir" into "Fir" -- .title() lowercases every letter but a word's first,
# so an acronym loses its own capitalisation. Verified visually in a real
# rendered PDF, not just in the API response.
_TYPE_LABEL = {
    ComplaintType.FIR: "FIR",
    ComplaintType.WRITTEN: "Written Complaint",
    ComplaintType.MAGISTRATE: "Magistrate Complaint",
    ComplaintType.CONSUMER: "Consumer Complaint",
    ComplaintType.CYBER: "Cyber Complaint",
}
_DISCLAIMER = (
    "DISCLAIMER: Generated by CaseIQ for legal-awareness purposes only. This is a DRAFT, "
    "not legal advice, and should be reviewed by a qualified advocate before submission."
)

# FIXED 2026-09-01: reportlab's built-in fonts (Helvetica etc.) are the PDF
# base-14 set -- Latin/WinAnsiEncoding only. Verified directly (not assumed):
# rendering Devanagari text through Helvetica and extracting the resulting
# PDF's text layer came back as literal U+25A0 (BLACK SQUARE) box-per-glyph --
# a silently broken "bilingual" PDF, not a working one, for any hi/mr/ta
# draft. The old Django pdf_service.py had this same gap (grep confirms it
# never registered a non-Latin font either), so this isn't a regression, but
# it was never actually fixed. Noto Sans Devanagari/Tamil (OFL-licensed,
# vendored under app/assets/fonts/) cover the scripts this app's `language`
# field claims to support; re-verified after registering them that the same
# round-trip produces the real Devanagari/Tamil text, not boxes.
#
# These are variable fonts (one file, weight axis) -- reportlab's TTFont
# registers a single static instance (the default weight), so there is no
# separate bold face for hi/mr/ta body text. Labels/headers for those
# languages render in the same regular weight rather than a faux or missing
# bold. Documented limitation, not silently papered over.
_FONT_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"
_FONTS_BY_LANG = {"en": "Helvetica", "hi": "NotoDevanagari", "mr": "NotoDevanagari", "ta": "NotoTamil"}
_fonts_registered = False


def _ensure_fonts_registered() -> None:
    global _fonts_registered
    if _fonts_registered:
        return
    pdfmetrics.registerFont(TTFont("NotoDevanagari", str(_FONT_DIR / "NotoSansDevanagari-Variable.ttf")))
    pdfmetrics.registerFont(TTFont("NotoTamil", str(_FONT_DIR / "NotoSansTamil-Variable.ttf")))
    _fonts_registered = True


def _styles(font: str) -> dict:
    base = getSampleStyleSheet()
    bold = "Helvetica-Bold" if font == "Helvetica" else font
    return {
        "body": ParagraphStyle("Body", parent=base["Normal"], fontName=font, fontSize=10, leading=15,
                               alignment=TA_JUSTIFY),
        "label": ParagraphStyle("Label", parent=base["Normal"], fontSize=10, fontName=bold,
                                 textColor=colors.HexColor("#1a1a2e")),
        "disclaimer": ParagraphStyle("Disc", parent=base["Normal"], fontSize=8, alignment=TA_CENTER,
                                     textColor=colors.HexColor("#cc0000"), fontName=bold),
        "sec": ParagraphStyle("Sec", fontSize=10, fontName=bold, textColor=colors.white),
    }


def _section_header(title: str, st: dict) -> Table:
    t = Table([[Paragraph(title, st["sec"])]], colWidths=[17 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#e94560")),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def _p(text: str) -> str:
    """Escape free-form text for reportlab's mini-XML before it goes in a
    Paragraph. FIXED 2026-09-01: incident_description etc. are free-text user
    input -- an unescaped '&', '<', or '>' (e.g. "AT&T", "salary < 20000")
    previously reached Paragraph() raw and would raise a parse error at
    render time, turning a normal complaint into a 500 on /download. Escape
    first, then reinstate the one tag this module deliberately injects
    (line breaks) after escaping is done, so it isn't escaped away too.
    """
    return escape(text).replace("\n", "<br/>")


def _draft_markup(text: str) -> str:
    """FIXED 2026-09-01: generate_complaint_draft's prompt doesn't forbid
    markdown, and the LLM reliably uses it (**bold**, "---" rules) -- verified
    in a real rendered PDF, where it came through as literal asterisks and
    dashes instead of formatting. Escape first (still free-form LLM text, same
    injection risk as any other field), then translate the one construct
    that's actually worth converting: **bold** -> reportlab's <b>. Standalone
    "---" rule lines are dropped rather than converted -- a Paragraph isn't a
    place to render an HRFlowable, and the surrounding _section_header bars
    already provide visual separation.
    """
    escaped = escape(text)
    escaped = re.sub(r"^\s*-{3,}\s*$", "", escaped, flags=re.MULTILINE)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", escaped)
    return escaped.replace("\n", "<br/>")


def _render(complaint: Complaint, path: str) -> bool:
    _ensure_fonts_registered()
    font = _FONTS_BY_LANG.get(complaint.language, "Helvetica")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    st = _styles(font)
    doc = SimpleDocTemplate(path, pagesize=A4, rightMargin=2 * cm, leftMargin=2 * cm,
                            topMargin=1.5 * cm, bottomMargin=2 * cm)
    story: list = []
    logo = ParagraphStyle("Logo", fontSize=20, fontName="Helvetica-Bold", alignment=TA_LEFT)
    story.append(Paragraph('<font color="#e94560">Case</font><font color="#1a1a2e">IQ</font>', logo))
    story.append(Paragraph("AI-Powered Legal Awareness Platform", st["body"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now():%d %B %Y}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    authority = _AUTHORITY.get(complaint.complaint_type, "The Concerned Authority")
    story.append(Paragraph("TO,", st["label"]))
    story.append(Paragraph(
        f"{_p(authority)},<br/>{_p(complaint.police_station_name) or '[Police Station]'}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))
    type_label = _TYPE_LABEL.get(complaint.complaint_type, complaint.complaint_type.value.replace("_", " ").title())
    story.append(Paragraph(
        f"<b>SUBJECT:</b> {_p(type_label)} "
        f"regarding incident at {_p(complaint.incident_location)} on {complaint.incident_date}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    story.append(_section_header("COMPLAINANT DETAILS", st))
    story.append(Spacer(1, 0.05 * inch))
    for lbl, val in [("Name", complaint.complainant_name), ("Address", complaint.complainant_address),
                     ("Phone", complaint.complainant_phone or "Not provided")]:
        story.append(Paragraph(f"<b>{lbl}:</b> {_p(val)}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    story.append(_section_header("INCIDENT DETAILS", st))
    story.append(Spacer(1, 0.05 * inch))
    story.append(Paragraph(f"<b>Description:</b> {_p(complaint.incident_description)}", st["body"]))
    if complaint.accused_details:
        story.append(Paragraph(f"<b>Accused:</b> {_p(complaint.accused_details)}", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    # GROUNDING, visible in the document itself, not just in the API response:
    # the exact sections retrieval matched (Complaint.retrieved_sections, set
    # in app/api/v1/complaints.py by the same semantic_search() /legal/query
    # uses), with their actual text -- or an explicit statement that none were
    # found, never a citation invented by the drafting LLM. See generate_complaint_draft.
    story.append(_section_header("LEGAL BASIS (matched by CaseIQ retrieval)", st))
    story.append(Spacer(1, 0.05 * inch))
    if complaint.retrieved_sections:
        for s in complaint.retrieved_sections:
            # Some corpus entries have no marginal_note (pre-existing ingestion
            # gap, e.g. BNS 85/86 -- see docs/evaluation.md); "Section 4 — :"
            # with an empty title looked broken, so the dash+title only
            # appears when there is one to show.
            heading = f"{s['act']} Section {s['section']}"
            if s["title"]:
                heading += f" — {s['title']}"
            story.append(Paragraph(f"<b>{_p(heading)}:</b> {_p(s['snippet'])}", st["body"]))
            story.append(Spacer(1, 0.06 * inch))
    else:
        story.append(Paragraph(
            "No section could be confidently matched to this incident by CaseIQ's retrieval. "
            "The applicable provisions should be identified by the reviewing officer or advocate "
            "before filing.", st["body"]))
    story.append(Spacer(1, 0.1 * inch))

    if complaint.generated_draft:
        story.append(_section_header("DRAFT TEXT", st))
        story.append(Spacer(1, 0.05 * inch))
        story.append(Paragraph(_draft_markup(complaint.generated_draft), st["body"]))
        story.append(Spacer(1, 0.1 * inch))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph("DECLARATION", st["label"]))
    story.append(Paragraph(
        "I solemnly declare that the information provided above is true and correct to the best of "
        "my knowledge. I understand that providing false information is punishable under law.", st["body"]))
    story.append(Spacer(1, 0.25 * inch))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#e94560")))
    story.append(Paragraph(_DISCLAIMER, st["disclaimer"]))
    doc.build(story)
    return True


async def generate_complaint_pdf(complaint: Complaint, path: str) -> bool:
    return await anyio.to_thread.run_sync(_render, complaint, path)
