# Generated by Django 5.1.4 on 2026-03-20 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(choices=[('fir', 'First Information Report (FIR)'), ('written_complaint', 'Written Complaint'), ('magistrate_complaint', 'Complaint to Magistrate'), ('consumer_complaint', 'Consumer Complaint'), ('cyber_complaint', 'Cyber Crime Complaint')], max_length=30)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_address', models.TextField()),
                ('complainant_phone', models.CharField(blank=True, max_length=15)),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=500)),
                ('incident_description', models.TextField()),
                ('accused_details', models.TextField(blank=True)),
                ('witnesses', models.TextField(blank=True)),
                ('evidence_description', models.TextField(blank=True)),
                ('relief_sought', models.TextField(blank=True)),
                ('applicable_sections', models.JSONField(default=list)),
                ('generated_draft', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('downloaded', 'Downloaded')], default='draft', max_length=20)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
