# Generated by Django 5.1.4 on 2026-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='police_station_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='complaint',
            name='police_station_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
