# Generated by Django 5.1.4 on 2026-03-20 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('legal_query', 'Legal Query Response'), ('complaint', 'Complaint Draft'), ('knowledge', 'Knowledge Base'), ('general', 'General')], max_length=20, unique=True)),
                ('english_text', models.TextField()),
                ('hindi_text', models.TextField(blank=True)),
                ('marathi_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disclaimer Template',
                'db_table': 'disclaimer_templates',
            },
        ),
        migrations.CreateModel(
            name='EthicsRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('block_phrase', 'Block Phrase'), ('require_disclaimer', 'Require Disclaimer'), ('flag_review', 'Flag for Review'), ('replace_content', 'Replace Content')], max_length=25)),
                ('pattern', models.TextField()),
                ('replacement', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ethics Rule',
                'db_table': 'ethics_rules',
            },
        ),
    ]
