# Generated by Django 6.0.2 on 2026-02-19 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laws", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("language", models.CharField(default="en", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for guest users",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_response", models.TextField()),
                ("similarity_scores", models.JSONField(blank=True, default=dict)),
                ("extracted_keywords", models.JSONField(blank=True, default=list)),
                ("next_steps", models.JSONField(blank=True, default=list)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_sections",
                    models.ManyToManyField(
                        blank=True, related_name="query_matches", to="laws.lawsection"
                    ),
                ),
                (
                    "query",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="queries.query",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["user", "status"], name="queries_que_user_id_512d0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["created_at"], name="queries_que_created_af74da_idx"
            ),
        ),
    ]
