/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/legal/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Query */
        post: operations["process_query_api_v1_legal_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sections
         * @description Browses the section IN FORCE as of `as_of` (default today) -- see
         *     app/services/retrieval.py's module docstring. Never queries the retired
         *     legal_sections table.
         *
         *     K2 hard rule applies HERE too, not just to semantic_search/keyword_search:
         *     a browse listing that showed IPC s.497 with no indication it's struck
         *     down would violate the same "never present as live law" rule through a
         *     different door. Found 2026-08-11 while finishing K7 -- this endpoint had
         *     no judicial_status join or exclusion at all until now.
         */
        get: operations["list_sections_api_v1_knowledge_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/sections/{act}/{section_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Section
         * @description K7's explicit, direct-citation lookup -- the one path in this app that
         *     CAN return a struck-down section, always with its judicial_status
         *     attached (never silently omitted, per K7), unlike list_sections/
         *     semantic_search/keyword_search which exclude struck-down entirely (K2's
         *     hard rule for organic/ranked results). Also carries the previous
         *     version's text when recently_amended, for K7's old/new diff.
         */
        get: operations["get_section_api_v1_knowledge_sections__act___section_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/semantic-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description REAL pgvector semantic search, as-of + judicial-status aware (Part K).
         */
        post: operations["search_api_v1_knowledge_semantic_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Complaint */
        post: operations["create_complaint_api_v1_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/complaints/{complaint_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_v1_complaints__complaint_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/complaints/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_complaints_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/awareness/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List News */
        get: operations["list_news_api_v1_awareness_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/awareness/news/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh News */
        post: operations["refresh_news_api_v1_awareness_news_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Logs */
        get: operations["list_logs_api_v1_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/corpus/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending */
        get: operations["list_pending_api_v1_admin_corpus_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/corpus/{staging_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_admin_corpus__staging_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/corpus/{staging_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_admin_corpus__staging_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/corpus/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_v1_admin_corpus_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sections/{act_code}/{section_number}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Section History */
        get: operations["section_history_api_v1_admin_sections__act_code___section_number__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveIn */
        ApproveIn: {
            /** Effective From */
            effective_from?: string | null;
            /**
             * Amending Act Name
             * @default
             */
            amending_act_name: string;
            /** Amending Act Year */
            amending_act_year?: number | null;
            /**
             * Gazette Ref
             * @default
             */
            gazette_ref: string;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** AuthOut */
        AuthOut: {
            user: components["schemas"]["UserOut"];
            tokens: components["schemas"]["Tokens"];
        };
        /** ChangePasswordIn */
        ChangePasswordIn: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** ComplaintIn */
        ComplaintIn: {
            complaint_type: components["schemas"]["ComplaintType"];
            /** Complainant Name */
            complainant_name: string;
            /** Complainant Address */
            complainant_address: string;
            /**
             * Complainant Phone
             * @default
             */
            complainant_phone: string;
            /**
             * Police Station Name
             * @default
             */
            police_station_name: string;
            /**
             * Police Station Address
             * @default
             */
            police_station_address: string;
            /**
             * Incident Date
             * Format: date
             */
            incident_date: string;
            /** Incident Location */
            incident_location: string;
            /** Incident Description */
            incident_description: string;
            /**
             * Accused Details
             * @default
             */
            accused_details: string;
            /**
             * Witnesses
             * @default
             */
            witnesses: string;
            /**
             * Evidence Description
             * @default
             */
            evidence_description: string;
            /**
             * Relief Sought
             * @default
             */
            relief_sought: string;
            /**
             * Applicable Sections
             * @default []
             */
            applicable_sections: string[];
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /** ComplaintOut */
        ComplaintOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            complaint_type: components["schemas"]["ComplaintType"];
            /** Complainant Name */
            complainant_name: string;
            /** Status */
            status: string;
            /** Generated Draft */
            generated_draft?: string | null;
            /**
             * Pdf Available
             * @default false
             */
            pdf_available: boolean;
            /** Download Url */
            download_url?: string | null;
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * ComplaintType
         * @enum {string}
         */
        ComplaintType: "fir" | "written_complaint" | "magistrate_complaint" | "consumer_complaint" | "cyber_complaint";
        /** CorpusVersionOut */
        CorpusVersionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Notes */
            notes: string;
            /** Section Count */
            section_count: number;
            /** Checksum */
            checksum: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JudicialStatusOut */
        JudicialStatusOut: {
            /** Status */
            status: string;
            /** Case Name */
            case_name: string;
            /** Citation */
            citation: string;
            /** Court */
            court: string;
            /** Decided On */
            decided_on?: string | null;
            /**
             * Scope Note
             * @default
             */
            scope_note: string;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** NewsOut */
        NewsOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string;
            /** Summary */
            summary: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Tags */
            tags: unknown[];
            /** Is Featured */
            is_featured: boolean;
        };
        /** PreviousVersionOut */
        PreviousVersionOut: {
            /** Version No */
            version_no: number;
            /** Section Text */
            section_text: string;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
        };
        /** QueryIn */
        QueryIn: {
            /** Query */
            query: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Incident Date */
            incident_date?: string | null;
            /** As Of */
            as_of?: string | null;
        };
        /** QueryOut */
        QueryOut: {
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Original Query */
            original_query: string;
            /** Conversational Summary */
            conversational_summary: string;
            /** Structured Data */
            structured_data: Record<string, never>;
            /** Confidence Score */
            confidence_score: number;
            /** Legal Sections */
            legal_sections: components["schemas"]["RetrievedSection"][];
            /** Language */
            language: string;
            /** Related Questions */
            related_questions: string[];
            /** Is Followup */
            is_followup: boolean;
            /** Processing Time Ms */
            processing_time_ms: number;
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Corpus Version Id */
            corpus_version_id?: string | null;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /** Phone */
            phone?: string | null;
            /**
             * Preferred Language
             * @default en
             */
            preferred_language: string;
        };
        /** RejectIn */
        RejectIn: {
            /** Reason */
            reason: string;
        };
        /** RetrievedSection */
        RetrievedSection: {
            /** Act */
            act: string;
            /** Section */
            section: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Similarity */
            similarity?: number | null;
            /** Version No */
            version_no?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Recently Amended
             * @default false
             */
            recently_amended: boolean;
            judicial_status?: components["schemas"]["JudicialStatusOut"] | null;
        };
        /**
         * SectionDetailOut
         * @description GET /knowledge/sections/{act}/{section} -- see that endpoint's
         *     docstring for why this is the one path that can surface a struck-down
         *     section rather than excluding it.
         */
        SectionDetailOut: {
            /** Act */
            act: string;
            /** Section */
            section: string;
            /** Title */
            title: string;
            /** Section Text */
            section_text: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Version No */
            version_no?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Recently Amended
             * @default false
             */
            recently_amended: boolean;
            previous_version?: components["schemas"]["PreviousVersionOut"] | null;
            judicial_status?: components["schemas"]["JudicialStatusOut"] | null;
        };
        /** SectionHistoryEntry */
        SectionHistoryEntry: {
            /** Version No */
            version_no: number;
            /** Marginal Note */
            marginal_note: string;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Is Repealed */
            is_repealed: boolean;
            /** Source Url */
            source_url: string | null;
            /** Parser Version */
            parser_version: string | null;
        };
        /** SectionOut */
        SectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Act */
            act: string;
            /** Section Number */
            section_number: string;
            /** Section Title */
            section_title: string;
            /** Section Text */
            section_text: string;
            /** Simplified Text */
            simplified_text: string;
            /** Category */
            category: string;
            /** Keywords */
            keywords: unknown[];
        };
        /** StagingChangeOut */
        StagingChangeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Act Code */
            act_code: string;
            /** Section Number */
            section_number: string;
            /** Source Url */
            source_url: string | null;
            /** Diff Summary */
            diff_summary: string;
            /** Status */
            status: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /** Tokens */
        Tokens: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Preferred Language */
            preferred_language: string;
            /** State */
            state?: string | null;
            /** District */
            district?: string | null;
            /** Is Verified */
            is_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tokens"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_query_api_v1_legal_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sections_api_v1_knowledge_sections_get: {
        parameters: {
            query?: {
                act?: string | null;
                /** @description keyword filter on title/text */
                q?: string | null;
                /** @description defaults to today -- see Part K K3 */
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_section_api_v1_knowledge_sections__act___section_number__get: {
        parameters: {
            query?: {
                /** @description defaults to today -- see Part K K3 */
                as_of?: string | null;
            };
            header?: never;
            path: {
                act: string;
                section_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_knowledge_semantic_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievedSection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_complaint_api_v1_complaints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_v1_complaints__complaint_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_complaints_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintOut"][];
                };
            };
        };
    };
    list_news_api_v1_awareness_news_get: {
        parameters: {
            query?: {
                featured?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_news_api_v1_awareness_news_refresh_post: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_api_v1_audit_logs_get: {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_api_v1_admin_corpus_pending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingChangeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_admin_corpus__staging_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staging_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_admin_corpus__staging_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staging_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_admin_corpus_versions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    section_history_api_v1_admin_sections__act_code___section_number__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_code: string;
                section_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
