# Generated by Django 5.1.4 on 2026-04-22 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ethicsviolationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_action_391715_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_ip_addr_b969fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_logs_is_flag_237410_idx',
        ),
        migrations.RenameField(
            model_name='ethicsviolationlog',
            old_name='filtered_content',
            new_name='query',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='processing_time_ms',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_data_hash',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='ethicsviolationlog',
            name='audit_log',
        ),
        migrations.RemoveField(
            model_name='ethicsviolationlog',
            name='original_content',
        ),
        migrations.RemoveField(
            model_name='ethicsviolationlog',
            name='severity',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ethicsviolationlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ethicsviolationlog',
            name='violation_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx'),
        ),
    ]
